apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: 'xxx'
  type: git
  url: 'xxx'
  password: 'xxx'
  username: 'xxx'
