global:
  domain: argo.fluffy.lst

configs:
  cm:
    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.fluffy.lst/realms/Nutty
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret
      requestedScopes: ["openid", "profile", "email"]
  params:
    server.insecure: true
  rbac:
    policy.default: role:admin
  secret:
    extra:
      oidc.keycloak.clientSecret: "SztNflS3LCRI5K5RfUYV7CUywJne6PiZ"

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - argo.fluffy.lst
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argo.fluffy.lst
  volumes:
    - name: custom-ca
      secret:
        secretName: keycloak-ca-cert
    - name: ca-certs
      emptyDir: {}
  volumeMounts:
    - name: ca-certs
      mountPath: /etc/ssl/certs
  initContainers:
    - name: update-ca-certs
      image: alpine:3.20
      command:
        - sh
        - -c
        - |
          apk add --no-cache ca-certificates >/dev/null
          cp /custom-ca/root.crt /usr/local/share/ca-certificates/keycloak-root-ca.crt
          cp /custom-ca/intermediate.crt /usr/local/share/ca-certificates/keycloak-intermediate-ca.crt
          update-ca-certificates
          cp -r /etc/ssl/certs/. /tmp/ca-certs/
      volumeMounts:
        - name: custom-ca
          mountPath: /custom-ca
        - name: ca-certs
          mountPath: /tmp/ca-certs